[package]
name = "sing_rivert"
version = "0.1.0"
edition = "2021"
description = "v2ray to sing-box config converter"
repository = "https://github.com/iyarivky/sing-rivert/"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
url = "2.5.2"
serde_json = "1.0.120"
